// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexico.flex

import java_cup.runtime.*;
import java.util.*;
import java.io.*;


@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\0\2\1\22\0\1\1\1\2\1\3"+
    "\1\0\1\4\1\5\1\6\1\0\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\11\20\1\21"+
    "\1\0\1\22\1\23\1\24\1\0\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\2\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\37\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\2\37\1\54\1\0"+
    "\1\55\1\56\1\57\1\0\1\60\3\27\1\61\1\62"+
    "\1\63\1\64\1\65\2\37\1\66\1\37\1\67\1\70"+
    "\2\37\1\71\1\72\1\73\2\37\1\74\3\37\1\75"+
    "\1\76\1\77\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\15"+
    "\1\16\1\17\1\20\1\21\12\22\1\23\1\24\1\25"+
    "\4\22\1\26\1\1\1\27\1\30\1\0\1\31\1\0"+
    "\1\32\1\33\1\0\1\34\1\35\1\36\5\22\1\37"+
    "\1\22\1\40\14\22\1\41\2\0\1\42\4\22\1\43"+
    "\1\44\14\22\1\0\1\45\1\22\1\46\4\22\1\47"+
    "\3\22\1\50\1\51\4\22\1\0\2\22\1\52\1\22"+
    "\1\53\1\22\1\54\2\22\1\55\1\22\1\0\1\56"+
    "\3\22\1\57\1\60\5\22\1\0\1\61\1\22\1\0"+
    "\1\22\12\0\1\62\2\0\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\u0140\0\100\0\u0180"+
    "\0\100\0\100\0\100\0\100\0\100\0\100\0\u01c0\0\100"+
    "\0\u0200\0\u0240\0\100\0\u0280\0\u02c0\0\u0300\0\u0340\0\u0380"+
    "\0\u03c0\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0540\0\u0580"+
    "\0\100\0\100\0\100\0\u05c0\0\u0600\0\u0640\0\u0680\0\100"+
    "\0\u06c0\0\100\0\100\0\u0100\0\100\0\u0700\0\100\0\u01c0"+
    "\0\u0740\0\100\0\100\0\100\0\u0780\0\u07c0\0\u0800\0\u0840"+
    "\0\u0880\0\u0340\0\u08c0\0\u0340\0\u0900\0\u0940\0\u0980\0\u09c0"+
    "\0\u0a00\0\u0a40\0\u0a80\0\u0ac0\0\u0b00\0\u0b40\0\u0b80\0\u0bc0"+
    "\0\100\0\u0c00\0\u0c40\0\u0740\0\u0c80\0\u0cc0\0\u0d00\0\u0d40"+
    "\0\u0340\0\u0340\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0"+
    "\0\u0f00\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u1040\0\u1080\0\100"+
    "\0\u10c0\0\u0340\0\u1100\0\u1140\0\u1180\0\u11c0\0\u0340\0\u1200"+
    "\0\u1240\0\u1280\0\u0340\0\u0340\0\u12c0\0\u1300\0\u1340\0\u1380"+
    "\0\u13c0\0\u1400\0\u1440\0\u0340\0\u1480\0\u0340\0\u14c0\0\u0340"+
    "\0\u1500\0\u1540\0\u0340\0\u1580\0\u15c0\0\u0340\0\u1600\0\u1640"+
    "\0\u1680\0\u0340\0\u0340\0\u16c0\0\u1700\0\u1740\0\u1780\0\u17c0"+
    "\0\u1800\0\u0340\0\u1840\0\u1880\0\u18c0\0\u1900\0\u1940\0\u1980"+
    "\0\u19c0\0\u1a00\0\u1a40\0\u1a80\0\u1ac0\0\u1b00\0\u1b40\0\100"+
    "\0\u1b80\0\u1bc0\0\100";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\2\3\27\1\30"+
    "\1\31\1\32\2\27\1\33\3\27\1\34\1\27\1\35"+
    "\1\36\1\37\1\27\1\40\3\27\1\41\1\42\1\43"+
    "\1\2\1\27\1\44\1\45\2\27\1\46\4\27\1\47"+
    "\2\27\1\50\1\51\1\52\101\0\1\3\121\0\1\53"+
    "\55\0\1\54\1\0\1\55\1\0\1\54\11\0\2\54"+
    "\4\0\27\54\4\0\15\54\14\0\1\56\74\0\1\57"+
    "\110\0\2\60\74\0\1\60\1\0\2\22\43\0\1\61"+
    "\30\0\1\60\1\0\2\22\102\0\1\62\77\0\1\63"+
    "\77\0\1\64\73\0\2\27\5\0\26\27\3\0\16\27"+
    "\22\0\2\27\5\0\4\27\1\65\21\27\3\0\16\27"+
    "\22\0\2\27\5\0\12\27\1\66\1\27\1\67\11\27"+
    "\3\0\16\27\22\0\2\27\5\0\12\27\1\70\2\27"+
    "\1\71\10\27\3\0\16\27\22\0\2\27\5\0\5\27"+
    "\1\72\6\27\1\73\3\27\1\74\5\27\3\0\16\27"+
    "\22\0\2\27\5\0\4\27\1\75\21\27\3\0\16\27"+
    "\22\0\2\27\5\0\17\27\1\76\6\27\3\0\16\27"+
    "\22\0\2\27\5\0\1\77\3\27\1\100\21\27\3\0"+
    "\16\27\22\0\2\27\5\0\7\27\1\101\11\27\1\102"+
    "\4\27\3\0\16\27\22\0\2\27\5\0\14\27\1\103"+
    "\11\27\3\0\16\27\22\0\2\27\5\0\26\27\3\0"+
    "\7\27\1\104\6\27\22\0\2\27\5\0\26\27\3\0"+
    "\7\27\1\105\6\27\22\0\2\27\5\0\26\27\3\0"+
    "\3\27\1\72\4\27\1\106\5\27\22\0\2\27\5\0"+
    "\26\27\3\0\5\27\1\107\6\27\1\110\1\27\101\0"+
    "\1\111\2\0\1\56\2\0\1\112\4\0\1\113\5\0"+
    "\2\56\5\0\26\56\4\0\15\56\22\0\2\114\5\0"+
    "\6\114\24\0\3\114\34\0\2\27\5\0\2\27\1\115"+
    "\23\27\3\0\16\27\22\0\2\27\5\0\20\27\1\116"+
    "\5\27\3\0\16\27\22\0\2\27\5\0\3\27\1\117"+
    "\22\27\3\0\16\27\22\0\2\27\5\0\15\27\1\120"+
    "\10\27\3\0\16\27\22\0\2\27\5\0\17\27\1\121"+
    "\6\27\3\0\16\27\22\0\2\27\5\0\21\27\1\122"+
    "\4\27\3\0\16\27\22\0\2\27\5\0\25\27\1\123"+
    "\3\0\16\27\22\0\2\27\5\0\15\27\1\124\10\27"+
    "\3\0\16\27\22\0\2\27\5\0\14\27\1\125\11\27"+
    "\3\0\16\27\22\0\2\27\5\0\16\27\1\126\7\27"+
    "\3\0\16\27\22\0\2\27\5\0\15\27\1\127\10\27"+
    "\3\0\16\27\22\0\2\27\5\0\4\27\1\130\12\27"+
    "\1\131\6\27\3\0\16\27\22\0\2\27\5\0\21\27"+
    "\1\132\4\27\3\0\16\27\22\0\2\27\5\0\26\27"+
    "\3\0\13\27\1\133\2\27\22\0\2\27\5\0\26\27"+
    "\3\0\11\27\1\134\4\27\22\0\2\27\5\0\26\27"+
    "\3\0\14\27\1\122\1\27\22\0\2\27\5\0\26\27"+
    "\3\0\11\27\1\135\4\27\22\0\2\27\5\0\26\27"+
    "\3\0\12\27\1\136\3\27\14\0\1\137\72\0\1\140"+
    "\112\0\2\27\5\0\23\27\1\141\2\27\3\0\16\27"+
    "\22\0\2\27\5\0\4\27\1\142\21\27\3\0\16\27"+
    "\22\0\2\27\5\0\3\27\1\143\4\27\1\144\5\27"+
    "\1\145\7\27\3\0\16\27\22\0\2\27\5\0\1\146"+
    "\25\27\3\0\16\27\22\0\2\27\5\0\21\27\1\147"+
    "\4\27\3\0\16\27\22\0\2\27\5\0\6\27\1\150"+
    "\17\27\3\0\16\27\22\0\2\27\5\0\6\27\1\151"+
    "\17\27\3\0\16\27\22\0\2\27\5\0\4\27\1\152"+
    "\21\27\3\0\16\27\22\0\2\27\5\0\24\27\1\153"+
    "\1\27\3\0\16\27\22\0\2\27\5\0\16\27\1\154"+
    "\7\27\3\0\16\27\22\0\2\27\5\0\10\27\1\155"+
    "\15\27\3\0\16\27\22\0\2\27\5\0\10\27\1\156"+
    "\15\27\3\0\16\27\22\0\2\27\5\0\26\27\3\0"+
    "\2\27\1\142\13\27\22\0\2\27\5\0\26\27\3\0"+
    "\1\27\1\157\14\27\22\0\2\27\5\0\26\27\3\0"+
    "\15\27\1\153\22\0\2\27\5\0\26\27\3\0\6\27"+
    "\1\160\7\27\4\0\1\137\7\0\1\161\5\0\2\137"+
    "\5\0\26\137\4\0\15\137\22\0\2\27\5\0\1\162"+
    "\25\27\3\0\16\27\22\0\2\27\5\0\4\27\1\163"+
    "\21\27\3\0\16\27\22\0\2\27\5\0\5\27\1\164"+
    "\20\27\3\0\16\27\22\0\2\27\5\0\17\27\1\165"+
    "\6\27\3\0\16\27\22\0\2\27\5\0\21\27\1\166"+
    "\4\27\3\0\16\27\22\0\2\27\5\0\17\27\1\167"+
    "\6\27\3\0\16\27\22\0\2\27\5\0\4\27\1\170"+
    "\21\27\3\0\16\27\22\0\2\27\5\0\1\171\25\27"+
    "\3\0\16\27\22\0\2\27\5\0\14\27\1\172\11\27"+
    "\3\0\16\27\22\0\2\27\5\0\12\27\1\173\13\27"+
    "\3\0\16\27\22\0\2\27\5\0\26\27\3\0\14\27"+
    "\1\166\1\27\22\0\2\27\5\0\26\27\3\0\10\27"+
    "\1\174\5\27\7\0\1\175\112\0\2\27\5\0\17\27"+
    "\1\176\6\27\3\0\16\27\22\0\2\27\5\0\2\27"+
    "\1\177\23\27\3\0\16\27\22\0\2\27\5\0\15\27"+
    "\1\200\10\27\3\0\16\27\22\0\2\27\5\0\1\201"+
    "\25\27\3\0\16\27\22\0\2\27\5\0\21\27\1\202"+
    "\4\27\3\0\16\27\22\0\2\27\5\0\6\27\1\203"+
    "\17\27\3\0\16\27\22\0\2\27\5\0\26\27\3\0"+
    "\4\27\1\203\11\27\4\0\1\175\7\0\1\113\5\0"+
    "\2\175\5\0\26\175\4\0\15\175\22\0\2\27\5\0"+
    "\23\27\1\204\2\27\3\0\16\27\22\0\2\27\5\0"+
    "\6\27\1\205\17\27\3\0\16\27\22\0\2\27\5\0"+
    "\13\27\1\206\12\27\3\0\16\27\22\0\2\27\5\0"+
    "\1\207\25\27\3\0\16\27\22\0\2\27\5\0\17\27"+
    "\1\210\6\27\3\0\16\27\20\0\1\211\1\0\2\27"+
    "\5\0\26\27\3\0\16\27\22\0\2\27\5\0\17\27"+
    "\1\212\6\27\3\0\16\27\22\0\2\27\5\0\1\213"+
    "\25\27\3\0\16\27\51\0\1\214\50\0\2\27\5\0"+
    "\13\27\1\215\12\27\3\0\16\27\35\0\1\216\62\0"+
    "\1\217\1\0\2\27\5\0\26\27\3\0\16\27\33\0"+
    "\1\220\115\0\1\221\100\0\1\222\62\0\1\223\103\0"+
    "\1\224\71\0\1\225\112\0\1\226\103\0\1\227\72\0"+
    "\1\230\73\0\1\231\104\0\1\232\76\0\1\233\35\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7168];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\1\1\6\11\1\1\1\11"+
    "\2\1\1\11\15\1\3\11\4\1\1\11\1\1\2\11"+
    "\1\0\1\11\1\0\1\11\1\1\1\0\3\11\24\1"+
    "\1\11\2\0\23\1\1\0\1\11\20\1\1\0\13\1"+
    "\1\0\13\1\1\0\2\1\1\0\1\1\12\0\1\11"+
    "\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // ===== Código Java insertado dentro de la clase generada =====

    // Instancia única de la tabla de símbolos (Singleton)
    private final TablaDeSimbolo tabla = TablaDeSimbolo.getInstance();
    private GuiAnalizador guiAnalizador;

    public void setGui(GuiAnalizador a) {
            this.guiAnalizador = a;
        }

    // Método auxiliar para agregar símbolos fácilmente
    private void agregarSimbolo(String nombre, String token, String valor) {
        tabla.addSimbolo(nombre, token, valor, nombre.length(), yyline + 1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new Symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* cualquier otro carácter desconocido se ignora */
            }
          // fall through
          case 52: break;
          case 2:
            { /* ignorar espacios */
            }
          // fall through
          case 53: break;
          case 3:
            { guiAnalizador.mostrarTexto("Token NOT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "NOT", null);
              return new Symbol(sym.NOT, yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 4:
            { guiAnalizador.mostrarTexto("Token MOD encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "MOD", null);
              return new Symbol(sym.MOD, yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 5:
            { guiAnalizador.mostrarTexto("Token PAREN_A encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PAREN_A", null);
              return new Symbol(sym.PAREN_A, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 6:
            { guiAnalizador.mostrarTexto("Token PAREN_C encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PAREN_C", null);
              return new Symbol(sym.PAREN_C, yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 7:
            { guiAnalizador.mostrarTexto("Token MULT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "MULT", null);
              return new Symbol(sym.MULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 8:
            { guiAnalizador.mostrarTexto("Token SUMA encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "SUMA", null);
              return new Symbol(sym.SUMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 9:
            { guiAnalizador.mostrarTexto("Token COMA encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "COMA", null);
              return new Symbol(sym.COMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 10:
            { guiAnalizador.mostrarTexto("Token RESTA encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "RESTA", null);
              return new Symbol(sym.RESTA, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 11:
            { guiAnalizador.mostrarTexto("Token PUNTO encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PUNTO", null);
              return new Symbol(sym.PUNTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 12:
            { guiAnalizador.mostrarTexto("Token DIV encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "DIV", null);
              return new Symbol(sym.DIV, yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 13:
            { guiAnalizador.mostrarTexto("Token CONST_INT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "CONST_INT", yytext());
              return new Symbol(sym.CONST_INT, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 14:
            { guiAnalizador.mostrarTexto("Token DATA_TYPE_ASSIGN encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "DATA_TYPE_ASSIGN", null);
               return new Symbol(sym.DATA_TYPE_ASSIGN, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 15:
            { guiAnalizador.mostrarTexto("Token MENOR encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "MENOR", null);
              return new Symbol(sym.MENOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 16:
            { guiAnalizador.mostrarTexto("Token ASIGN encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "ASIGN", null);
              return new Symbol(sym.ASIGN, yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 17:
            { guiAnalizador.mostrarTexto("Token MAYOR encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "MAYOR", null);
              return new Symbol(sym.MAYOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 18:
            { guiAnalizador.mostrarTexto("Token ID encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "ID", null);
              return new Symbol(sym.ID, yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 19:
            { guiAnalizador.mostrarTexto("Token CLASP_A encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "CLASP_A", null);
              return new Symbol(sym.CLASP_A, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 20:
            { guiAnalizador.mostrarTexto("Token CLASP_C encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "CLASP_C", null);
              return new Symbol(sym.CLASP_C, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 21:
            { guiAnalizador.mostrarTexto("Token POT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "POT", null);
              return new Symbol(sym.POT, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 22:
            { guiAnalizador.mostrarTexto("Token KEY_A encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "KEY_A", null);
              return new Symbol(sym.KEY_A, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 23:
            { guiAnalizador.mostrarTexto("Token KEY_C encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "KEY_C", null);
              return new Symbol(sym.KEY_C, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 24:
            { guiAnalizador.mostrarTexto("Token DISTINTO encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "DISTINTO", null);
              return new Symbol(sym.DISTINTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 25:
            { guiAnalizador.mostrarTexto("Token CONST_STR encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "CONST_STR", yytext());
              return new Symbol(sym.CONST_STR, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 26:
            { guiAnalizador.mostrarTexto("Token AND encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "AND", null);
              return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 27:
            { guiAnalizador.mostrarTexto("Token CONST_FLOAT encontrado, Lexema "+ yytext());
                agregarSimbolo(yytext(), "CONST_FLOAT", yytext());
              return new Symbol(sym.CONST_FLOAT, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 28:
            { guiAnalizador.mostrarTexto("Token MENOR_IGUAL encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "MENOR_IGUAL", null);
              return new Symbol(sym.MENOR_IGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 29:
            { guiAnalizador.mostrarTexto("Token IGUAL encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "IGUAL", null);
              return new Symbol(sym.IGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 30:
            { guiAnalizador.mostrarTexto("Token MAYOR_IGUAL encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "MAYOR_IGUAL", null);
              return new Symbol(sym.MAYOR_IGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 31:
            { guiAnalizador.mostrarTexto("Token PR_IF encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_IF", null);
              return new Symbol(sym.PR_IF, yyline, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 32:
            { guiAnalizador.mostrarTexto("Token PR_IS encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_IS", null);
              return new Symbol(sym.PR_IS, yyline, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 33:
            { guiAnalizador.mostrarTexto("Token OR encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "OR", null);
              return new Symbol(sym.OR, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 34:
            { guiAnalizador.mostrarTexto("Token CONST_HEX encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "CONST_HEX", yytext());
              return new Symbol(sym.CONST_HEX, yyline, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 35:
            { guiAnalizador.mostrarTexto("Token PR_FOR encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_FOR", null);
              return new Symbol(sym.PR_FOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 36:
            { guiAnalizador.mostrarTexto("Token PR_INT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_INT", null);
              return new Symbol(sym.PR_INT, yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 37:
            { /* ignorar comentarios */
            }
          // fall through
          case 88: break;
          case 38:
            { guiAnalizador.mostrarTexto("Token PR_ELSE encontrado, Lexema "+ yytext());
                agregarSimbolo(yytext(), "PR_ELSE", null);
              return new Symbol(sym.PR_ELSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 39:
            { guiAnalizador.mostrarTexto("Token PR_NEXT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_NEXT", null);
              return new Symbol(sym.PR_NEXT, yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 40:
            { guiAnalizador.mostrarTexto("Token SHOW encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "SHOW", null);
              return new Symbol(sym.SHOW, yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 41:
            { guiAnalizador.mostrarTexto("Token PR_STEP encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_STEP", null);
              return new Symbol(sym.PR_STEP, yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 42:
            { guiAnalizador.mostrarTexto("Token PR_ENDIF encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_ENDIF", null);
              return new Symbol(sym.PR_ENDIF, yyline, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 43:
            { guiAnalizador.mostrarTexto("Token PR_FLOAT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_FLOAT", null);
              return new Symbol(sym.PR_FLOAT, yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 44:
            { guiAnalizador.mostrarTexto("Token PR_RANGE encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_RANGE", null);
              return new Symbol(sym.PR_RANGE, yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 45:
            { guiAnalizador.mostrarTexto("Token PR_UNTIL encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_UNTIL", null);
              return new Symbol(sym.PR_UNTIL, yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 46:
            { guiAnalizador.mostrarTexto("Token DEC_VAR encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "DEC_VAR", null);
              return new Symbol(sym.DEC_VAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 47:
            { guiAnalizador.mostrarTexto("Token PR_REPEAT encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_REPEAT", null);
              return new Symbol(sym.PR_REPEAT, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 48:
            { guiAnalizador.mostrarTexto("Token PR_STRING encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_STRING", null);
              return new Symbol(sym.PR_STRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 49:
            { guiAnalizador.mostrarTexto("Token END_DEC_VAR encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "END_DEC_VAR", null);
              return new Symbol(sym.END_DEC_VAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 50:
            { guiAnalizador.mostrarTexto("Token PR_PROGRAM encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_PROGRAM", null);
              return new Symbol(sym.PR_PROGRAM, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 51:
            { guiAnalizador.mostrarTexto("Token PR_ENDPROGRAM encontrado, Lexema "+ yytext());
              agregarSimbolo(yytext(), "PR_ENDPROGRAM", null);
              return new Symbol(sym.PR_ENDPROGRAM, yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
