// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/Users/facun/IdeaProjects/TrabajoIntegradorTEOI/src/Lexico.flex

import java_cup.runtime.*;
import java_cup.sym;

import java.util.*;


@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";
  private GuiAnalizador guiAnalizador;

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\0\2\1\22\0\1\1\1\2\1\3"+
    "\1\0\1\4\1\5\2\0\1\6\1\7\1\10\1\11"+
    "\1\12\1\0\1\13\1\14\1\15\11\16\1\17\1\0"+
    "\1\20\1\21\1\22\2\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\2\32\1\34\1\32"+
    "\1\35\1\36\1\37\1\32\1\40\1\41\1\42\1\43"+
    "\1\44\1\32\1\45\2\32\1\46\1\0\1\47\1\50"+
    "\1\51\1\0\1\52\3\24\1\53\1\54\1\32\1\55"+
    "\1\56\2\32\1\57\1\32\1\60\1\61\3\32\1\62"+
    "\1\63\2\32\1\64\3\32\1\65\1\0\1\66\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\11\21\1\22\1\23\1\24\5\21\1\25"+
    "\1\26\1\27\1\0\1\30\1\0\1\31\1\32\1\0"+
    "\1\33\1\34\1\35\1\36\4\21\1\37\1\40\12\21"+
    "\1\0\1\30\3\21\1\41\7\21\1\42\2\21\1\43"+
    "\1\21\1\44\2\21\1\45\2\21\1\46\2\21\1\47"+
    "\3\21\1\50\1\51\1\21\1\52\1\53\1\54\1\55"+
    "\1\21\1\56\2\21\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\67\0\67"+
    "\0\67\0\67\0\u014a\0\67\0\u0181\0\67\0\u01b8\0\u01ef"+
    "\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7"+
    "\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\67\0\67\0\67"+
    "\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\67\0\67\0\67"+
    "\0\334\0\67\0\u0604\0\67\0\u0181\0\u063b\0\67\0\67"+
    "\0\67\0\67\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u0302\0\u0302"+
    "\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf"+
    "\0\u0906\0\u093d\0\u0974\0\u063b\0\u09ab\0\u09e2\0\u0a19\0\u0302"+
    "\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0302"+
    "\0\u0bd1\0\u0c08\0\67\0\u0c3f\0\u0302\0\u0c76\0\u0cad\0\u0302"+
    "\0\u0ce4\0\u0d1b\0\u0302\0\u0d52\0\u0d89\0\u0302\0\u0dc0\0\u0df7"+
    "\0\u0e2e\0\u0302\0\u0302\0\u0e65\0\u0302\0\u0302\0\u0302\0\u0302"+
    "\0\u0e9c\0\u0302\0\u0ed3\0\u0f0a\0\u0302";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\3\25\1\26\1\27\1\30\2\25"+
    "\1\31\1\25\1\32\2\25\1\33\1\34\1\25\1\35"+
    "\2\25\1\36\1\37\1\40\1\2\1\25\1\41\1\42"+
    "\1\25\1\43\3\25\1\44\1\25\1\45\1\46\1\47"+
    "\70\0\1\3\106\0\1\50\46\0\1\51\1\0\1\52"+
    "\11\0\2\51\4\0\23\51\4\0\13\51\12\0\1\53"+
    "\77\0\1\54\62\0\2\55\63\0\1\55\1\0\2\20"+
    "\36\0\1\56\24\0\1\55\1\0\2\20\71\0\1\57"+
    "\66\0\1\60\66\0\1\61\66\0\1\62\62\0\2\25"+
    "\4\0\23\25\3\0\14\25\17\0\2\25\4\0\4\25"+
    "\1\63\16\25\3\0\14\25\17\0\2\25\4\0\11\25"+
    "\1\64\1\65\10\25\3\0\14\25\17\0\2\25\4\0"+
    "\13\25\1\66\7\25\3\0\14\25\17\0\2\25\4\0"+
    "\5\25\1\67\10\25\1\70\4\25\3\0\14\25\17\0"+
    "\2\25\4\0\4\25\1\71\16\25\3\0\14\25\17\0"+
    "\2\25\4\0\1\72\3\25\1\73\16\25\3\0\14\25"+
    "\17\0\2\25\4\0\17\25\1\74\3\25\3\0\14\25"+
    "\17\0\2\25\4\0\12\25\1\75\10\25\3\0\14\25"+
    "\17\0\2\25\4\0\23\25\3\0\6\25\1\76\5\25"+
    "\17\0\2\25\4\0\23\25\3\0\6\25\1\77\5\25"+
    "\17\0\2\25\4\0\23\25\3\0\3\25\1\67\3\25"+
    "\1\100\4\25\17\0\2\25\4\0\23\25\3\0\4\25"+
    "\1\101\7\25\17\0\2\25\4\0\23\25\3\0\4\25"+
    "\1\102\7\25\3\0\1\53\6\0\1\103\4\0\2\53"+
    "\4\0\23\53\4\0\13\53\17\0\2\104\4\0\6\104"+
    "\21\0\3\104\27\0\2\25\4\0\2\25\1\105\20\25"+
    "\3\0\14\25\17\0\2\25\4\0\16\25\1\106\4\25"+
    "\3\0\14\25\17\0\2\25\4\0\3\25\1\107\17\25"+
    "\3\0\14\25\17\0\2\25\4\0\15\25\1\110\5\25"+
    "\3\0\14\25\17\0\2\25\4\0\22\25\1\111\3\0"+
    "\14\25\17\0\2\25\4\0\12\25\1\112\10\25\3\0"+
    "\14\25\17\0\2\25\4\0\14\25\1\113\6\25\3\0"+
    "\14\25\17\0\2\25\4\0\4\25\1\114\16\25\3\0"+
    "\14\25\17\0\2\25\4\0\17\25\1\115\3\25\3\0"+
    "\14\25\17\0\2\25\4\0\23\25\3\0\11\25\1\116"+
    "\2\25\17\0\2\25\4\0\23\25\3\0\10\25\1\117"+
    "\3\25\17\0\2\25\4\0\23\25\3\0\12\25\1\120"+
    "\1\25\17\0\2\25\4\0\23\25\3\0\10\25\1\121"+
    "\3\25\17\0\2\25\4\0\23\25\3\0\5\25\1\122"+
    "\6\25\6\0\1\123\77\0\2\25\4\0\21\25\1\124"+
    "\1\25\3\0\14\25\17\0\2\25\4\0\4\25\1\125"+
    "\16\25\3\0\14\25\17\0\2\25\4\0\3\25\1\126"+
    "\4\25\1\127\12\25\3\0\14\25\17\0\2\25\4\0"+
    "\17\25\1\130\3\25\3\0\14\25\17\0\2\25\4\0"+
    "\6\25\1\131\14\25\3\0\14\25\17\0\2\25\4\0"+
    "\4\25\1\132\16\25\3\0\14\25\17\0\2\25\4\0"+
    "\14\25\1\133\6\25\3\0\14\25\17\0\2\25\4\0"+
    "\10\25\1\134\12\25\3\0\14\25\17\0\2\25\4\0"+
    "\23\25\3\0\2\25\1\125\11\25\17\0\2\25\4\0"+
    "\23\25\3\0\1\25\1\135\12\25\17\0\2\25\4\0"+
    "\23\25\3\0\13\25\1\136\17\0\2\25\4\0\23\25"+
    "\3\0\6\25\1\137\5\25\17\0\2\25\4\0\1\140"+
    "\22\25\3\0\14\25\17\0\2\25\4\0\4\25\1\141"+
    "\16\25\3\0\14\25\17\0\2\25\4\0\5\25\1\142"+
    "\15\25\3\0\14\25\17\0\2\25\4\0\4\25\1\143"+
    "\16\25\3\0\14\25\17\0\2\25\4\0\1\144\22\25"+
    "\3\0\14\25\17\0\2\25\4\0\11\25\1\145\11\25"+
    "\3\0\14\25\17\0\2\25\4\0\23\25\3\0\12\25"+
    "\1\146\1\25\17\0\2\25\4\0\23\25\3\0\2\25"+
    "\1\147\11\25\17\0\2\25\4\0\15\25\1\150\5\25"+
    "\3\0\14\25\17\0\2\25\4\0\2\25\1\151\20\25"+
    "\3\0\14\25\17\0\2\25\4\0\17\25\1\152\3\25"+
    "\3\0\14\25\17\0\2\25\4\0\21\25\1\153\1\25"+
    "\3\0\14\25\17\0\2\25\4\0\1\154\22\25\3\0"+
    "\14\25\17\0\2\25\4\0\15\25\1\155\5\25\3\0"+
    "\14\25\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3905];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\4\11\1\1\1\11\1\1\1\11"+
    "\17\1\3\11\5\1\3\11\1\0\1\11\1\0\1\11"+
    "\1\1\1\0\4\11\20\1\1\0\17\1\1\11\32\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in, GuiAnalizador guiAnalizador) {
    this.zzReader = in;
    this.guiAnalizador = guiAnalizador;

  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
          // fall through
          case 48: break;
          case 2:
            { /* no se realiza accion por lo tanto se ignoran*/
            }
          // fall through
          case 49: break;
          case 3:
            { guiAnalizador.mostrarTexto("Token NOT encontrado, Lexema "+ yytext());
            }
          // fall through
          case 50: break;
          case 4:
            { guiAnalizador.mostrarTexto("Token MOD encontrado, Lexema "+ yytext());
            }
          // fall through
          case 51: break;
          case 5:
            { guiAnalizador.mostrarTexto("Token PAREN_A encontrado, Lexema "+ yytext());
            }
          // fall through
          case 52: break;
          case 6:
            { guiAnalizador.mostrarTexto("Token PAREN_C encontrado, Lexema "+ yytext());
            }
          // fall through
          case 53: break;
          case 7:
            {guiAnalizador.mostrarTexto("Token MULT encontrado, Lexema "+ yytext());
            }
          // fall through
          case 54: break;
          case 8:
            { guiAnalizador.mostrarTexto("Token SUMA encontrado, Lexema "+ yytext());
            }
          // fall through
          case 55: break;
          case 9:
            { guiAnalizador.mostrarTexto("Token COMA encontrado, Lexema "+ yytext());
            }
          // fall through
          case 56: break;
          case 10:
            { guiAnalizador.mostrarTexto("Token PUNTO encontrado, Lexema "+ yytext());
            }
          // fall through
          case 57: break;
          case 11:
            { guiAnalizador.mostrarTexto("Token DIV encontrado, Lexema "+ yytext());
            }
          // fall through
          case 58: break;
          case 12:
            { guiAnalizador.mostrarTexto("Token CONST_INT, encontrado Lexema "+ yytext());
            }
          // fall through
          case 59: break;
          case 13:
            { guiAnalizador.mostrarTexto("Token DATA_TYPE_ASSIGN encontrado, Lexema "+ yytext());
            }
          // fall through
          case 60: break;
          case 14:
            { guiAnalizador.mostrarTexto("Token MENOR encontrado, Lexema "+ yytext());
            }
          // fall through
          case 61: break;
          case 15:
            { guiAnalizador.mostrarTexto("Token ASIGN encontrado, Lexema "+ yytext());
            }
          // fall through
          case 62: break;
          case 16:
            {guiAnalizador.mostrarTexto("Token MAYOR encontrado, Lexema "+ yytext());
            }
          // fall through
          case 63: break;
          case 17:
            {guiAnalizador.mostrarTexto("Token ID encontrado, Lexema "+ yytext());
            }
          // fall through
          case 64: break;
          case 18:
            { guiAnalizador.mostrarTexto("Token CLASP_A encontrado, Lexema "+ yytext());
            }
          // fall through
          case 65: break;
          case 19:
            { guiAnalizador.mostrarTexto("Token CLASP_C encontrado, Lexema "+ yytext());
            }
          // fall through
          case 66: break;
          case 20:
            { guiAnalizador.mostrarTexto("Token POT encontrado, Lexema "+ yytext());
            }
          // fall through
          case 67: break;
          case 21:
            { guiAnalizador.mostrarTexto("Token KEY_A encontrado, Lexema "+ yytext());
            }
          // fall through
          case 68: break;
          case 22:
            { guiAnalizador.mostrarTexto("Token KEY_C encontrado, Lexema "+ yytext());
            }
          // fall through
          case 69: break;
          case 23:
            { guiAnalizador.mostrarTexto("Token DISTINTO encontrado, Lexema "+ yytext());
            }
          // fall through
          case 70: break;
          case 24:
            { guiAnalizador.mostrarTexto("Token CONST_STR, encontrado Lexema "+ yytext());
            }
          // fall through
          case 71: break;
          case 25:
            { guiAnalizador.mostrarTexto("Token MASIGUAL encontrado, Lexema "+ yytext());
            }
          // fall through
          case 72: break;
          case 26:
            { guiAnalizador.mostrarTexto("Token CONST_FLOAT, encontrado Lexema "+ yytext());
            }
          // fall through
          case 73: break;
          case 27:
            { guiAnalizador.mostrarTexto("Token CONST encontrado, Lexema "+ yytext());
            }
          // fall through
          case 74: break;
          case 28:
            {guiAnalizador.mostrarTexto("Token MENOR_IGUAL encontrado, Lexema "+ yytext());
            }
          // fall through
          case 75: break;
          case 29:
            { guiAnalizador.mostrarTexto("Token IGUAL encontrado, Lexema "+ yytext());
            }
          // fall through
          case 76: break;
          case 30:
            { guiAnalizador.mostrarTexto("Token MAYOR_IGUAL encontrado, Lexema "+ yytext());
            }
          // fall through
          case 77: break;
          case 31:
            { guiAnalizador.mostrarTexto("Token PR_IF encontrado, Lexema "+yytext());
            }
          // fall through
          case 78: break;
          case 32:
            { guiAnalizador.mostrarTexto("Token PR_IS encontrado, Lexema "+yytext());
            }
          // fall through
          case 79: break;
          case 33:
            {guiAnalizador.mostrarTexto("Token PR_FOR encontrado, Lexema "+yytext());
            }
          // fall through
          case 80: break;
          case 34:
            {guiAnalizador.mostrarTexto("Token PR_INT encontrado, Lexema "+yytext());
            }
          // fall through
          case 81: break;
          case 35:
            { /* No se realiza accion por lo tanto se ignoran*/
            }
          // fall through
          case 82: break;
          case 36:
            {guiAnalizador.mostrarTexto("Token PR_ELSE encontrado, Lexema "+yytext());
            }
          // fall through
          case 83: break;
          case 37:
            {guiAnalizador.mostrarTexto("Token PR_NEXT encontrado, Lexema "+yytext());
            }
          // fall through
          case 84: break;
          case 38:
            {guiAnalizador.mostrarTexto("Token PR_STEP encontrado, Lexema "+yytext());
            }
          // fall through
          case 85: break;
          case 39:
            { guiAnalizador.mostrarTexto("Token SHOW encontrado, Lexema "+yytext());
            }
          // fall through
          case 86: break;
          case 40:
            { guiAnalizador.mostrarTexto("Token PR_ENDIF encontrado, Lexema "+yytext());
            }
          // fall through
          case 87: break;
          case 41:
            { guiAnalizador.mostrarTexto("Token PR_RANGE encontrado, Lexema "+yytext());
            }
          // fall through
          case 88: break;
          case 42:
            { guiAnalizador.mostrarTexto("Token PR_UNTIL encontrado, Lexema "+yytext());
            }
          // fall through
          case 89: break;
          case 43:
            {guiAnalizador.mostrarTexto("Token PR_FLOAT encontrado, Lexema "+yytext());
            }
          // fall through
          case 90: break;
          case 44:
            {guiAnalizador.mostrarTexto("Token PR_WHILE encontrado, Lexema "+yytext());
            }
          // fall through
          case 91: break;
          case 45:
            { guiAnalizador.mostrarTexto("Token DEC_VAR encontrado, Lexema "+ yytext());
            }
          // fall through
          case 92: break;
          case 46:
            { guiAnalizador.mostrarTexto("Token PR_REPEAT encontrado, Lexema "+yytext());
            }
          // fall through
          case 93: break;
          case 47:
            { guiAnalizador.mostrarTexto("Token END_DEC_VAR encontrado, Lexema "+ yytext());
            }
          // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
