
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 41;
  public static final int SHOW = 27;
  public static final int PR_INT = 24;
  public static final int POT = 8;
  public static final int PR_IS = 13;
  public static final int MULT = 5;
  public static final int PR_FOR = 12;
  public static final int END_DEC_VAR = 11;
  public static final int RESTA = 9;
  public static final int PR_ENDIF = 20;
  public static final int PR_IF = 18;
  public static final int PR_ELSE = 19;
  public static final int PR_WHILE = 17;
  public static final int AND = 43;
  public static final int NOT = 42;
  public static final int PR_FLOAT = 25;
  public static final int IGUAL = 36;
  public static final int OR = 44;
  public static final int DIV = 6;
  public static final int DEC_VAR = 10;
  public static final int SUMA = 4;
  public static final int CONST_FLOAT = 47;
  public static final int DATA_TYPE_ASSIGN = 2;
  public static final int ID = 45;
  public static final int EOF = 0;
  public static final int PR_PROGRAM = 23;
  public static final int PR_STEP = 15;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MENOR = 39;
  public static final int PR_STRING = 26;
  public static final int MOD = 7;
  public static final int MAYOR = 40;
  public static final int CLASP_C = 29;
  public static final int CLASP_A = 28;
  public static final int PUNTO = 34;
  public static final int MAYOR_IGUAL = 38;
  public static final int KEY_C = 33;
  public static final int KEY_A = 32;
  public static final int PR_RANGE = 14;
  public static final int ASIGN = 3;
  public static final int PAREN_C = 31;
  public static final int CONST_STR = 49;
  public static final int PAREN_A = 30;
  public static final int MENOR_IGUAL = 37;
  public static final int PR_UNTIL = 22;
  public static final int PR_REPEAT = 21;
  public static final int PR_NEXT = 16;
  public static final int CONST_INT = 48;
  public static final int CONST_HEX = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DATA_TYPE_ASSIGN",
  "ASIGN",
  "SUMA",
  "MULT",
  "DIV",
  "MOD",
  "POT",
  "RESTA",
  "DEC_VAR",
  "END_DEC_VAR",
  "PR_FOR",
  "PR_IS",
  "PR_RANGE",
  "PR_STEP",
  "PR_NEXT",
  "PR_WHILE",
  "PR_IF",
  "PR_ELSE",
  "PR_ENDIF",
  "PR_REPEAT",
  "PR_UNTIL",
  "PR_PROGRAM",
  "PR_INT",
  "PR_FLOAT",
  "PR_STRING",
  "SHOW",
  "CLASP_A",
  "CLASP_C",
  "PAREN_A",
  "PAREN_C",
  "KEY_A",
  "KEY_C",
  "PUNTO",
  "COMA",
  "IGUAL",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "MENOR",
  "MAYOR",
  "DISTINTO",
  "NOT",
  "AND",
  "OR",
  "ID",
  "CONST_HEX",
  "CONST_FLOAT",
  "CONST_INT",
  "CONST_STR"
  };
}

